
const CONFIG={owner:'nepdogg',repo:'allstargalaxysoccer',branch:'main',dataPath:'data/master-content.json'};
const SECTION_SCHEMAS={
 players:{title:'Players',array:'players',imageField:'photo',imageFolder:'images/team/players',fields:[['name','Player name','text',true],['number','Jersey number','text'],['position','Position','text'],['photo','Player photo path','text'],['status','Status','select',['published','hidden']],['order','Display order','number']]},
 games:{title:'Games',array:'games',imageField:'cardImage',imageFolder:'images/media/latest-games',fields:[['season','Season','text',true],['gameNumber','Game number','number',true],['opponent','Opponent','text',true],['date','Date','date'],['time','Time','time'],['location','Location','text'],['result','Result, e.g. W (3-1)','text'],['fullMatch','Full Match URL','url'],['highlights','Highlights URL','url'],['slideshow','Slideshow URL','url'],['cardImage','Custom card image','text'],['group','Carousel group','select',['latest','archive']],['status','Status','select',['published','hidden']],['order','Display order','number']]},
 seasons:{title:'Seasons',array:'seasons',imageField:'cardImage',imageFolder:'images/seasons',fields:[['title','Season title','text',true],['subtitle','Subtitle','text'],['dateRange','Date range','text'],['league','League','text'],['fullMatches','Full Matches playlist','url'],['highlights','Highlights playlist','url'],['slideshows','Slideshows playlist','url'],['cardImage','Custom card image','text'],['status','Status','select',['published','hidden']],['order','Display order','number']]},
 playlists:{title:'Playlists',array:'playlists',imageField:'cardImage',imageFolder:'images/media/playlists',fields:[['title','Playlist title','text',true],['description','Description','textarea'],['url','YouTube playlist URL','url'],['category','Category','select',['core','archive','shorts','best','goals','saves','assists','plays']],['locations','Carousel location','locationselect'],['cardImage','Custom card image','text'],['status','Status','select',['published','hidden']],['order','Display order','number']]},
 news:{title:'News',array:'news',imageField:'image',imageFolder:'images/news',fields:[['title','Headline','text',true],['date','Date','date'],['summary','News text','textarea'],['link','Optional link','url'],['category','Category','text'],['image','News image','text'],['status','Status','select',['published','hidden','placeholder']],['order','Display order','number']]}
};
let state={data:null,sha:null,dirty:false,section:null,editIndex:-1,pendingFiles:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){return sessionStorage.getItem('asgGithubToken')||''} function authHeaders(){return {'Accept':'application/vnd.github+json','Authorization':`Bearer ${token()}`,'X-GitHub-Api-Version':'2022-11-28'}}
function setStatus(msg,type=''){const el=$('#statusbar');if(el){el.textContent=msg;el.className='statusbar '+type}}
async function ghGet(path){const url=`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${path}?ref=${encodeURIComponent(CONFIG.branch)}&_=${Date.now()}`;const r=await fetch(url,{headers:{...authHeaders(),'Cache-Control':'no-cache','Pragma':'no-cache'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.json()}
async function ghPut(path,content,message,sha){const body={message,content,branch:CONFIG.branch};if(sha)body.sha=sha;const r=await fetch(`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${path}`,{method:'PUT',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.json()}
function decode64(s){return decodeURIComponent(escape(atob(s.replace(/\n/g,''))))} function encode64(s){return btoa(unescape(encodeURIComponent(s)))}
async function connect(){if(!token()){location.href='index.html';return}setStatus('Connecting to GitHub…');try{const f=await ghGet(CONFIG.dataPath);state.sha=f.sha;state.data=JSON.parse(decode64(f.content));setStatus(`Connected to ${CONFIG.owner}/${CONFIG.repo} • master-content.json loaded`,'ok');renderPage()}catch(e){setStatus('Connection failed: '+e.message,'bad')}}
function slug(s){return String(s||'item').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'item'}
function nextId(arr,prefix){let n=1;const ids=new Set(arr.map(x=>x.id));while(ids.has(`${prefix}-${String(n).padStart(2,'0')}`))n++;return `${prefix}-${String(n).padStart(2,'0')}`}
function markDirty(){state.dirty=true;const p=$('#pendingLabel');if(p)p.textContent='Unpublished changes';}
function titleFor(x,s){return x.name||x.title||(s==='games'?`${x.season||''} Game ${x.gameNumber||''}`:x.id)}
function subFor(x,s){if(s==='players')return `#${x.number||'—'} • ${x.position||'Position not set'}`;if(s==='games')return `${x.opponent||'Opponent'} • ${x.result||'No result'} • ${x.status}`;if(s==='playlists')return `${x.category||''} • ${(x.locations||[]).join?.(', ')||x.locations||''}`;return `${x.status||''} • Order ${x.order??''}`}
function renderManager(section){state.section=section;const schema=SECTION_SCHEMAS[section],arr=state.data[schema.array]||[];$('#pageTitle').textContent=schema.title;$('#content').innerHTML=`<div class="admin-actions" style="margin-bottom:15px"><button class="btn primary" id="addBtn">Add ${schema.title.replace(/s$/,'')}</button><button class="btn" id="publishBtn">Publish All Changes</button><span class="pending" id="pendingLabel">${state.dirty?'Unpublished changes':''}</span></div><div class="item-list">${arr.map((x,i)=>`<div class="item-row ${x.status==='hidden'?'is-hidden':''}"><div><div class="item-title">${esc(titleFor(x,section))}</div><div class="item-sub">${esc(subFor(x,section))}</div></div><div class="row-actions"><button class="btn small" data-edit="${i}">Edit</button><button class="btn small" data-toggle="${i}">${x.status==='hidden'?'Restore':'Hide'}</button><button class="btn small danger" data-delete="${i}">Delete</button></div></div>`).join('')}</div>`;$('#addBtn').onclick=()=>openForm(-1);$('#publishBtn').onclick=publish;$$('[data-edit]').forEach(b=>b.onclick=()=>openForm(+b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>{const x=arr[+b.dataset.toggle];x.status=x.status==='hidden'?'published':'hidden';markDirty();renderManager(section)});$$('[data-delete]').forEach(b=>b.onclick=()=>{const i=+b.dataset.delete;if(confirm('Permanently delete this item? Hide is safer.')){arr.splice(i,1);markDirty();renderManager(section)}})}
function playlistLocationValue(val){const a=Array.isArray(val)?val:String(val||'').split(',').map(x=>x.trim()).filter(Boolean);const has=x=>a.includes(x);if(has('home-best')&&has('media-archive'))return 'best-and-archive';if(has('home-best'))return 'home-best';if(has('season-archive')&&has('latest-season-playlists'))return 'season-and-latest';if(has('latest-season-playlists'))return 'latest-season-playlists';if(has('season-archive'))return 'season-archive';return 'media-archive'}
function playlistLocationsFromValue(val){const map={'media-archive':['media-archive'],'home-best':['home-best'],'best-and-archive':['home-best','media-archive'],'season-archive':['season-archive'],'latest-season-playlists':['latest-season-playlists'],'season-and-latest':['season-archive','latest-season-playlists']};return map[val]||['media-archive']}
function inputHtml(field,val){const [key,label,type,rule]=field;const required=rule===true?'required':'';if(type==='select'){const opts=rule.map(o=>`<option ${String(val)===o?'selected':''}>${esc(o)}</option>`).join('');return `<div class="field"><label>${label}</label><select name="${key}">${opts}</select></div>`}if(type==='locationselect'){const current=playlistLocationValue(val);const options=[['media-archive','Archive carousel'],['home-best','Best Of carousel only'],['best-and-archive','Best Of + Archive carousels'],['season-archive','Season Archive carousel'],['latest-season-playlists','Latest Season Playlists carousel'],['season-and-latest','Season Archive + Latest Season Playlists']];return `<div class="field"><label>${label}</label><select name="${key}">${options.map(([v,t])=>`<option value="${v}" ${current===v?'selected':''}>${t}</option>`).join('')}</select><div class="help">Choose exactly where this playlist card should appear.</div></div>`}if(type==='textarea')return `<div class="field full"><label>${label}</label><textarea name="${key}">${esc(val||'')}</textarea></div>`;return `<div class="field"><label>${label}</label><input name="${key}" type="${type}" value="${esc(val??'')}" ${required}></div>`}
function safeImagePath(schema,form,item,uploadFile){const pathInput=form.querySelector(`[name="${schema.imageField}"]`);let requested=String(pathInput?.value||'').trim().replace(/^\/+/, '');let fileName='';if(requested){fileName=requested.split('/').pop().replace(/\.[^.]+$/,'')+'.png'}else if(uploadFile?.name){const originalBase=uploadFile.name.replace(/\.[^.]+$/,'');fileName=`${slug(originalBase)}.png`}else if(item?.[schema.imageField]){fileName=String(item[schema.imageField]).split('/').pop().replace(/\.[^.]+$/,'')+'.png'}else{const name=form.querySelector('[name="name"]')?.value||form.querySelector('[name="title"]')?.value||form.querySelector('[name="id"]')?.value||item.id;fileName=`${slug(name)}.png`}return `${schema.imageFolder}/${fileName}`}
function openForm(index){const schema=SECTION_SCHEMAS[state.section],arr=state.data[schema.array],item=index>=0?structuredClone(arr[index]):{status:'published',order:arr.length+1};let uploadedPath='';state.editIndex=index;if(index<0)item.id=nextId(arr,state.section.replace(/s$/,''));$('#modalTitle').textContent=(index>=0?'Edit ':'Add ')+schema.title.replace(/s$/,'');$('#editForm').innerHTML=`<div class="form-grid"><div class="field"><label>ID</label><input name="id" value="${esc(item.id||'')}" required></div>${schema.fields.map(f=>inputHtml(f,item[f[0]])).join('')}<div class="field full"><label>Upload optional PNG image</label><input id="imageUpload" type="file" accept="image/png,image/jpeg,image/webp"><div class="help">Images are converted to PNG in your browser. Leave the image-path field blank. The uploaded file name is used automatically and converted to PNG. You may enter a custom path only when needed.</div><img id="imagePreview" class="upload-preview" hidden></div></div><div class="admin-actions" style="margin-top:18px"><button class="btn primary" type="submit">Save Form</button><button class="btn" type="button" id="cancelForm">Cancel</button></div>`;const form=$('#editForm');form.onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),obj={...item};for(const [k,v] of fd.entries()){obj[k]=['order','gameNumber'].includes(k)?Number(v):v}if(uploadedPath)obj[schema.imageField]=uploadedPath;if(state.section==='playlists')obj.locations=playlistLocationsFromValue(obj.locations);if(index>=0)arr[index]=obj;else arr.push(obj);markDirty();closeModal();renderManager(state.section)};$('#cancelForm').onclick=closeModal;const up=$('#imageUpload');up.onchange=async()=>{if(!up.files[0])return;const result=await fileToPng(up.files[0]);uploadedPath=safeImagePath(schema,form,item,up.files[0]);item[schema.imageField]=uploadedPath;state.pendingFiles=state.pendingFiles.filter(f=>f.path!==uploadedPath);state.pendingFiles.push({path:uploadedPath,base64:result.base64});$('#imagePreview').src=result.url;$('#imagePreview').hidden=false;const pathInput=form.querySelector(`[name="${schema.imageField}"]`);if(pathInput)pathInput.value=uploadedPath};$('#editModal').classList.add('open')}
function closeModal(){$('#editModal').classList.remove('open')}
async function fileToPng(file){const bmp=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;canvas.getContext('2d').drawImage(bmp,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/png',.92));const url=URL.createObjectURL(blob),buf=await blob.arrayBuffer(),bytes=new Uint8Array(buf);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return {url,base64:btoa(binary)}}
async function publish(){
 if(!state.data)return;
 setStatus('Publishing images and master-content.json…');
 try{
  for(const file of state.pendingFiles){
   let sha;
   try{sha=(await ghGet(file.path)).sha}catch(e){}
   await ghPut(file.path,file.base64,`Admin: update ${file.path}`,sha)
  }
  state.data.version=Number(state.data.version||0)+1;
  state.data.updated=new Date().toISOString().slice(0,10);
  const encoded=encode64(JSON.stringify(state.data,null,2));
  // Always request the newest file SHA immediately before publishing. This
  // prevents GitHub 409 conflicts when another admin tab or a recent update
  // changed master-content.json after this page was opened.
  let r=null,lastError=null;
  // GitHub may briefly return a stale SHA through browser/CDN caching. Fetch with
  // no-store and retry a few times with a fresh cache-busting request.
  for(let attempt=1;attempt<=4;attempt++){
   const latest=await ghGet(CONFIG.dataPath);
   try{
    r=await ghPut(CONFIG.dataPath,encoded,attempt===1?'Admin: publish website content update':`Admin: publish website content update (retry ${attempt-1})`,latest.sha);
    break
   }catch(err){
    lastError=err;
    if(!String(err.message).startsWith('409:')||attempt===4)throw err;
    await new Promise(resolve=>setTimeout(resolve,500*attempt))
   }
  }
  if(!r)throw lastError||new Error('Publish failed after automatic retries')
  state.sha=r.content.sha;
  state.pendingFiles=[];
  state.dirty=false;
  setStatus('Published successfully. GitHub Pages will update shortly.','ok');
  renderPage()
 }catch(e){
  setStatus('Publish failed: '+e.message,'bad')
 }
}
function queueAssetUpload(inp){if(!inp.files[0])return Promise.resolve();return fileToPng(inp.files[0]).then(r=>{const path=inp.dataset.assetPath,key=inp.dataset.assetKey;state.data.assets=state.data.assets||{};state.data.assets[key]=path;state.pendingFiles=state.pendingFiles.filter(f=>f.path!==path);state.pendingFiles.push({path,base64:r.base64});markDirty();setStatus(`${key} ready to publish.`,'ok')})}
function assetField(key,label,path,current){return `<div class="field"><label>${label}</label><input data-asset-path="${path}" data-asset-key="${key}" type="file" accept="image/png,image/jpeg,image/webp"><div class="help">Current: ${esc(current||path)}</div></div>`}
function renderScheduleAssets(){const a=state.data.assets||{},d=state.data.display||{};$('#pageTitle').textContent='Schedule & Standings';$('#content').innerHTML=`<div class="panel"><h3>Schedule and standings images</h3><p class="help">Upload replacement PNG files for the public Schedule page. These controls are separate from the global website graphics.</p><div class="form-grid">${assetField('scheduleImage','Schedule PNG','images/schedule/schedule.png',a.scheduleImage)}${assetField('standingsImage','Standings PNG','images/schedule/standings.png',a.standingsImage)}<div class="field"><label>Schedule visibility</label><select id="scheduleVisible"><option value="true" ${d.scheduleVisible!==false?'selected':''}>Visible</option><option value="false" ${d.scheduleVisible===false?'selected':''}>Hidden</option></select></div><div class="field"><label>Standings visibility</label><select id="standingsVisible"><option value="true" ${d.standingsVisible!==false?'selected':''}>Visible</option><option value="false" ${d.standingsVisible===false?'selected':''}>Hidden</option></select></div></div><div class="admin-actions" style="margin-top:18px"><button class="btn primary" id="publishSchedule">Publish Schedule & Standings</button></div></div>`;$$('[data-asset-key]').forEach(inp=>inp.onchange=()=>queueAssetUpload(inp));$('#scheduleVisible').onchange=e=>{state.data.display=state.data.display||{};state.data.display.scheduleVisible=e.target.value==='true';markDirty()};$('#standingsVisible').onchange=e=>{state.data.display=state.data.display||{};state.data.display.standingsVisible=e.target.value==='true';markDirty()};$('#publishSchedule').onclick=publish}
function renderAssets(){const a=state.data.assets||{};$('#pageTitle').textContent='Website Graphics';$('#content').innerHTML=`<div class="panel"><h3>Global website graphics</h3><p class="help">Manage reusable default artwork. Schedule and standings are managed on their own page.</p><div class="form-grid">${assetField('mediaBackground','Default media-card background','generated/media-card-background.png',a.mediaBackground)}${assetField('playerSilhouette','Default player silhouette','images/team/players/player-silhouette.png',a.playerSilhouette)}${assetField('liveDefaultImage','Default livestream image','images/live/live-default.png',a.liveDefaultImage)}</div><div class="admin-actions" style="margin-top:18px"><button class="btn primary" id="publishAssets">Publish Website Graphics</button></div></div>`;$$('[data-asset-key]').forEach(inp=>inp.onchange=()=>queueAssetUpload(inp));$('#publishAssets').onclick=publish}
function renderLive(){const l=state.data.live||{};$('#pageTitle').textContent='Livestream';$('#content').innerHTML=`<form class="panel" id="liveForm"><div class="form-grid">${[['title','Stream title','text'],['opponent','Opponent','text'],['scheduledStart','Scheduled start','datetime-local'],['scheduledEnd','Expected end','datetime-local'],['location','Location','text'],['url','YouTube livestream URL','url'],['replayUrl','Replay URL','url'],['thumbnail','Thumbnail path','text']].map(f=>inputHtml(f,l[f[0]])).join('')}<div class="field"><label>Control mode</label><select name="mode"><option ${l.mode==='automatic'?'selected':''}>automatic</option><option ${l.mode==='manual'?'selected':''}>manual</option></select></div><div class="field"><label>Manual status</label><select name="status">${['offline','scheduled','live','ended','replay'].map(x=>`<option ${l.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Description</label><textarea name="description">${esc(l.description||'')}</textarea></div><div class="field full"><label>Upload livestream thumbnail</label><input id="liveUpload" type="file" accept="image/png,image/jpeg,image/webp"></div></div><div class="admin-actions" style="margin-top:18px"><button class="btn primary" type="submit">Save Livestream</button><button class="btn" type="button" id="publishLive">Publish</button></div></form>`;$('#liveForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);Object.assign(state.data.live,Object.fromEntries(fd.entries()));markDirty();setStatus('Livestream settings saved locally. Publish when ready.','ok')};$('#liveUpload').onchange=async e=>{if(!e.target.files[0])return;const r=await fileToPng(e.target.files[0]),path='images/live/current-livestream.png';state.data.live.thumbnail=path;state.pendingFiles=state.pendingFiles.filter(f=>f.path!==path);state.pendingFiles.push({path,base64:r.base64});markDirty()};$('#publishLive').onclick=publish}
function renderDashboard(){const counts=Object.entries(SECTION_SCHEMAS).map(([k,s])=>[k,s.title,(state.data[s.array]||[]).filter(x=>x.status!=='hidden').length]);$('#pageTitle').textContent='Dashboard';$('#content').innerHTML=`<div class="dashboard-grid">${counts.map(([k,t,n])=>`<a class="dash-card" href="${k}.html"><strong>${t}</strong><span>${n} visible items</span></a>`).join('')}<a class="dash-card" href="schedule.html"><strong>Schedule & Standings</strong><span>Upload replacement PNG files</span></a><a class="dash-card" href="livestream.html"><strong>Livestream</strong><span>Schedule, status and replay</span></a><a class="dash-card" href="graphics.html"><strong>Website Graphics</strong><span>Default backgrounds and silhouettes</span></a></div>`}
function renderPage(){const page=document.body.dataset.page||'dashboard';$$('.admin-nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));if(SECTION_SCHEMAS[page])renderManager(page);else if(page==='schedule')renderScheduleAssets();else if(page==='graphics')renderAssets();else if(page==='livestream')renderLive();else renderDashboard()}
function initCommon(){$('#menuBtn')?.addEventListener('click',()=>$('.admin-sidebar').classList.toggle('open'));$('#logoutBtn')?.addEventListener('click',()=>{sessionStorage.removeItem('asgGithubToken');location.href='index.html'});$('#modalClose')?.addEventListener('click',closeModal);connect()}
window.AdminCMS={initCommon,publish};
