(() => {
  "use strict";
  const CFG={owner:"nepdogg",repo:"allstargalaxysoccer",branch:"main",path:"data/site-settings.json"};
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const token=()=>sessionStorage.getItem("asgGithubToken")||"";
  const headers=()=>({Accept:"application/vnd.github+json",Authorization:`Bearer ${token()}`,"X-GitHub-Api-Version":"2022-11-28"});
  const decode=s=>decodeURIComponent(escape(atob(s.replace(/\n/g,""))));
  const encode=s=>btoa(unescape(encodeURIComponent(s)));
  let state={data:null,sha:null,dirty:false};
  function status(message,type=""){const el=$("#statusbar");el.textContent=message;el.className=`statusbar ${type}`;}
  async function getFile(){const r=await fetch(`https://api.github.com/repos/${CFG.owner}/${CFG.repo}/contents/${CFG.path}?ref=${CFG.branch}`,{headers:headers()});if(!r.ok)throw new Error(await r.text());return r.json();}
  async function putFile(content,sha){const r=await fetch(`https://api.github.com/repos/${CFG.owner}/${CFG.repo}/contents/${CFG.path}`,{method:"PUT",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({message:"Admin: update status ticker banner",content:encode(content),sha,branch:CFG.branch})});if(!r.ok)throw new Error(await r.text());return r.json();}
  function bar(){state.data.announcementBar=state.data.announcementBar||{enabled:true,intervalSeconds:6,transition:"fade",priorityMessage:"",messages:[]};return state.data.announcementBar;}
  function mark(){state.dirty=true;const p=$("#pendingLabel");if(p)p.textContent="Unpublished changes";}
  function row(item={},index=0){return `<div class="panel announcement-row" data-row="${index}"><div class="form-grid"><div class="field"><label>Icon</label><input data-key="icon" value="${esc(item.icon||"⭐")}" maxlength="8"></div><div class="field full"><label>Complete message</label><input data-key="text" value="${esc(item.text||"")}" placeholder="The complete message visitors will see"></div><div class="field full"><label>Destination link</label><input data-key="href" value="${esc(item.href||"")}" placeholder="media.html or media.html#galaxy-shuffle"></div></div><button class="btn danger-outline remove-message" type="button">Remove Message</button></div>`;}
  function render(){const a=bar();$("#content").innerHTML=`<div class="v2-banner"><strong>Sticky Announcement Bar</strong><span>Each complete message appears at once, remains visible, then fades to the next message.</span></div><div class="admin-actions unified-workflow-bar"><button class="btn" id="saveDraft">Save Draft</button><button class="btn" id="preview">Preview Website</button><button class="btn primary" id="publish">Publish</button><button class="btn danger-outline" id="cancel">Cancel</button><span class="pending" id="pendingLabel">${state.dirty?"Unpublished changes":"No unpublished changes"}</span></div><section class="panel"><h3>Banner Behavior</h3><div class="form-grid"><div class="field"><label>Banner status</label><select id="enabled"><option value="true" ${a.enabled!==false?"selected":""}>Enabled</option><option value="false" ${a.enabled===false?"selected":""}>Hidden</option></select></div><div class="field"><label>Seconds per message</label><input id="interval" type="number" min="3" max="30" value="${Number(a.intervalSeconds)||6}"></div><div class="field"><label>Transition</label><select id="transition"><option value="fade" ${a.transition!=="slide"?"selected":""}>Fade</option><option value="slide" ${a.transition==="slide"?"selected":""}>Subtle slide</option></select></div><div class="field full"><label>Priority message (optional)</label><input id="priority" value="${esc(a.priorityMessage||"")}" placeholder="When entered, this message displays first"></div></div></section><section><div class="panel"><div class="admin-actions"><h3 style="margin-right:auto">Rotating Messages</h3><button class="btn" id="addMessage" type="button">+ Add Message</button></div><div id="messageRows">${a.messages.map(row).join("")}</div></div></section>`;
    bind();}
  function sync(){const a=bar();a.enabled=$("#enabled").value==="true";a.intervalSeconds=Math.max(3,Math.min(30,Number($("#interval").value)||6));a.transition=$("#transition").value;a.priorityMessage=$("#priority").value.trim();a.messages=[...document.querySelectorAll(".announcement-row")].map(r=>({icon:r.querySelector('[data-key="icon"]').value.trim()||"⭐",text:r.querySelector('[data-key="text"]').value.trim(),href:r.querySelector('[data-key="href"]').value.trim()})).filter(x=>x.text);state.data.version=222;}
  function bind(){document.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",mark));$("#addMessage").onclick=()=>{sync();bar().messages.push({icon:"⭐",text:"",href:""});mark();render();};document.querySelectorAll(".remove-message").forEach((b,i)=>b.onclick=()=>{sync();bar().messages.splice(i,1);mark();render();});$("#saveDraft").onclick=()=>{sync();sessionStorage.setItem("asgDraftSiteSettings",JSON.stringify(state.data));sessionStorage.setItem("asgPreviewSiteSettings",JSON.stringify(state.data));status("Announcement draft saved — not published.","ok");};$("#preview").onclick=()=>{sync();sessionStorage.setItem("asgPreviewSiteSettings",JSON.stringify(state.data));window.open("../index.html?adminPreview=1","_blank");};$("#cancel").onclick=()=>{if(state.dirty&&!confirm("Discard unpublished announcement changes?"))return;location.href="dashboard.html";};$("#publish").onclick=publish;}
  async function publish(){try{sync();status("Publishing status / ticker banner…");await window.ASGBackup?.create("Before announcement banner publish");const latest=await getFile();const result=await putFile(JSON.stringify(state.data,null,2)+"\n",latest.sha);state.sha=result.content.sha;state.dirty=false;sessionStorage.removeItem("asgPreviewSiteSettings");status("Status / ticker banner published.","ok");render();}catch(error){status("Publish failed: "+error.message,"bad");}}
  async function init(){if(!token()){location.href="index.html";return;}try{const f=await getFile();state.sha=f.sha;state.data=JSON.parse(decode(f.content));status("Status / ticker manager connected.","ok");render();}catch(error){status("Could not load settings: "+error.message,"bad");}}
  document.addEventListener("DOMContentLoaded",()=>{$("#menuBtn").onclick=()=>document.querySelector(".admin-sidebar").classList.toggle("open");$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("asgGithubToken");location.href="index.html";};init();});
})();