(() => {
'use strict';
const CONFIG={owner:'nepdogg',repo:'allstargalaxysoccer',branch:'main',path:'data/master-content.json'};
const GAME_TYPES=[['full-match','Full Match'],['highlights','Highlights'],['slideshow','Slideshow'],['player-of-the-game','Player of the Game'],['goal-of-the-game','Goal of the Game'],['save-of-the-game','Save of the Game'],['play-of-the-game','Play of the Game'],['assist-of-the-game','Assist of the Game']];
const SEASON_TYPES=[['all-goals','All Goals of the Season'],['top-10-goals','Top 10 Goals of the Season'],['goal-of-season','Goal of the Season'],['all-saves','All Saves of the Season'],['top-10-saves','Top 10 Saves of the Season'],['save-of-season','Save of the Season'],['all-assists','All Assists of the Season'],['top-10-assists','Top 10 Assists of the Season'],['assist-of-season','Assist of the Season'],['all-plays','All Plays of the Season'],['top-10-plays','Top 10 Plays of the Season'],['play-of-season','Play of the Season'],['players-of-season','Players of the Season'],['top-10-players','Top 10 Players of the Season'],['player-of-season','Player of the Season']];
const PLATFORMS=[['youtube','YouTube'],['facebook','Facebook'],['instagram','Instagram'],['threads','Threads'],['x','X'],['tiktok','TikTok']];
const STATUS=[['not_started','Not Started'],['in_progress','In Progress'],['complete','Complete'],['na','N/A']];
const SOCIAL=[['not_started','Not Posted'],['prepared','Prepared'],['scheduled','Scheduled'],['posted','Posted'],['na','N/A']];
let data,sha,dirty=false,view='games',filter='all',selectedSeason='all';
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=()=>sessionStorage.getItem('asgGithubToken')||'';
const headers=()=>({'Accept':'application/vnd.github+json','Authorization':`Bearer ${token()}`,'X-GitHub-Api-Version':'2022-11-28'});
const decode=s=>decodeURIComponent(escape(atob(s.replace(/\n/g,'')))); const encode=s=>btoa(unescape(encodeURIComponent(s)));
function status(msg,type=''){const e=$('#statusbar');e.textContent=msg;e.className='statusbar '+type}
async function get(){const r=await fetch(`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${CONFIG.path}?ref=${CONFIG.branch}&_=${Date.now()}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw Error(`${r.status}: ${await r.text()}`);return r.json()}
async function put(){const current=await get();data.version=Number(data.version||0)+1;data.updated=new Date().toISOString().slice(0,10);data.production.updated=new Date().toISOString();const r=await fetch(`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${CONFIG.path}`,{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({message:'V4 Production Control Center update',content:encode(JSON.stringify(data,null,2)),branch:CONFIG.branch,sha:current.sha})});if(!r.ok)throw Error(`${r.status}: ${await r.text()}`);sha=(await r.json()).content.sha;dirty=false;status('Production tracker published successfully. GitHub Pages will update shortly.','ok');render()}
function blankTask(){return {status:'not_started',url:'',notes:'',social:Object.fromEntries(PLATFORMS.map(([id])=>[id,'not_started']))}}
function ensure(){data.production=data.production||{schemaVersion:1,gameTemplate:GAME_TYPES.map(([id,title])=>({id,title,required:['full-match','highlights','slideshow','player-of-the-game'].includes(id)})),seasonTemplate:SEASON_TYPES.map(([id,title])=>({id,title,required:true})),socialPlatforms:PLATFORMS.map(([id,title])=>({id,title,enabled:true})),games:{},seasons:{}};data.production.games=data.production.games||{};data.production.seasons=data.production.seasons||{};(data.games||[]).forEach(g=>{const rec=data.production.games[g.id]||(data.production.games[g.id]={tasks:{},notes:'',priority:'normal'});GAME_TYPES.forEach(([id])=>rec.tasks[id]=rec.tasks[id]||blankTask())});(data.seasons||[]).forEach(s=>{if(s.title==='Future Season')return;const rec=data.production.seasons[s.id]||(data.production.seasons[s.id]={tasks:{},notes:''});SEASON_TYPES.forEach(([id])=>rec.tasks[id]=rec.tasks[id]||blankTask())})}
function percent(tasks,types){let done=0,total=0;types.forEach(([id])=>{const s=tasks[id]?.status||'not_started';if(s==='na')return;total++;if(s==='complete')done++});return total?Math.round(done/total*100):100}
function socialPercent(tasks,types){let done=0,total=0;types.forEach(([id])=>PLATFORMS.forEach(([p])=>{const s=tasks[id]?.social?.[p]||'not_started';if(s==='na')return;total++;if(s==='posted')done++}));return total?Math.round(done/total*100):100}
function badge(s){return `<span class="v4-status-dot s-${s}"></span>`}
function options(list,current){return list.map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${l}</option>`).join('')}
function summary(){const games=(data.games||[]).filter(g=>g.status!=='hidden');const gp=games.map(g=>percent(data.production.games[g.id].tasks,GAME_TYPES));const gamePct=gp.length?Math.round(gp.reduce((a,b)=>a+b,0)/gp.length):0;const social=games.map(g=>socialPercent(data.production.games[g.id].tasks,GAME_TYPES));const socialPct=social.length?Math.round(social.reduce((a,b)=>a+b,0)/social.length):0;const complete=gp.filter(x=>x===100).length;const missing=[];games.forEach(g=>GAME_TYPES.forEach(([id,title])=>{const s=data.production.games[g.id].tasks[id].status;if(s==='not_started')missing.push(`${g.season} Game ${g.gameNumber}: ${title}`)}));return {games,gamePct,socialPct,complete,missing}}
function progressCard(label,value,detail){return `<div class="v4-metric"><div class="v4-metric-head"><strong>${label}</strong><b>${value}%</b></div><div class="v4-progress"><i style="width:${value}%"></i></div><small>${detail}</small></div>`}
function render(){ensure();const sum=summary();const seasons=[...new Set((data.games||[]).map(g=>g.season).filter(Boolean))];$('#content').innerHTML=`
<div class="v4-hero"><div><span class="v2-pill">ALLSTAR GALAXY V4.0 • STAGE 1</span><h3>Production Control Center</h3><p>Track every game video, every season video, and every social-media post from one screen.</p></div><div class="admin-actions"><button class="btn" id="syncBtn">Sync Missing Tasks</button><button class="btn primary" id="publishV4">Publish Changes</button></div></div>
<div class="v4-summary-grid">${progressCard('Game Production',sum.gamePct,`${sum.complete} of ${sum.games.length} games complete`)}${progressCard('Social Distribution',sum.socialPct,'All enabled platforms across game videos')}${progressCard('Season Production',seasonOverall(),'End-of-season video checklist')}</div>
<div class="v4-tabs"><button data-view="games" class="${view==='games'?'active':''}">Game Tracker</button><button data-view="seasons" class="${view==='seasons'?'active':''}">Season Tracker</button><button data-view="next" class="${view==='next'?'active':''}">Next Tasks <span>${sum.missing.length}</span></button></div>
<div class="v4-toolbar"><select id="seasonFilter"><option value="all">All Seasons</option>${seasons.map(s=>`<option ${selectedSeason===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="statusFilter"><option value="all">All Completion Levels</option><option value="incomplete" ${filter==='incomplete'?'selected':''}>Incomplete Only</option><option value="complete" ${filter==='complete'?'selected':''}>Complete Only</option></select><span class="pending">${dirty?'Unpublished changes':''}</span></div>
<div id="v4Body">${view==='games'?renderGames():view==='seasons'?renderSeasons():renderNext(sum.missing)}</div>`;
$('#publishV4').onclick=async()=>{try{status('Publishing production tracker…');await put()}catch(e){status('Publish failed: '+e.message,'bad')}};$('#syncBtn').onclick=()=>{ensure();mark();render()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#seasonFilter').onchange=e=>{selectedSeason=e.target.value;render()};$('#statusFilter').onchange=e=>{filter=e.target.value;render()};bindControls()}
function seasonOverall(){const list=(data.seasons||[]).filter(s=>data.production.seasons[s.id]);if(!list.length)return 0;return Math.round(list.map(s=>percent(data.production.seasons[s.id].tasks,SEASON_TYPES)).reduce((a,b)=>a+b,0)/list.length)}
function renderGames(){let games=(data.games||[]).filter(g=>g.status!=='hidden'&&(selectedSeason==='all'||g.season===selectedSeason));games.sort((a,b)=>String(b.season).localeCompare(String(a.season))||Number(a.gameNumber)-Number(b.gameNumber));games=games.filter(g=>{const p=percent(data.production.games[g.id].tasks,GAME_TYPES);return filter==='all'||(filter==='complete'?p===100:p<100)});if(!games.length)return '<div class="panel"><p>No games match this filter.</p></div>';return games.map(g=>{const rec=data.production.games[g.id],p=percent(rec.tasks,GAME_TYPES),sp=socialPercent(rec.tasks,GAME_TYPES);return `<section class="v4-project" data-game="${esc(g.id)}"><header><div><small>${esc(g.season)}</small><h3>Game ${esc(g.gameNumber)} vs ${esc(g.opponent||'Opponent')}</h3><span>${esc(g.result||'Result not entered')}</span></div><div class="v4-project-score"><b>${p}%</b><small>Production</small><b>${sp}%</b><small>Social</small></div></header><div class="v4-task-grid">${GAME_TYPES.map(([id,title])=>taskRow('game',g.id,id,title,rec.tasks[id])).join('')}</div></section>`}).join('')}
function renderSeasons(){let list=(data.seasons||[]).filter(s=>data.production.seasons[s.id]&&(selectedSeason==='all'||s.title===selectedSeason));if(!list.length)return '<div class="panel"><p>No seasons match this filter.</p></div>';return list.map(s=>{const rec=data.production.seasons[s.id],p=percent(rec.tasks,SEASON_TYPES);return `<section class="v4-project" data-season="${esc(s.id)}"><header><div><small>END OF SEASON</small><h3>${esc(s.title)}</h3><span>15 standard season productions</span></div><div class="v4-project-score"><b>${p}%</b><small>Complete</small></div></header><div class="v4-task-grid">${SEASON_TYPES.map(([id,title])=>taskRow('season',s.id,id,title,rec.tasks[id])).join('')}</div></section>`}).join('')}
function taskRow(kind,parent,id,title,t){return `<div class="v4-task" data-kind="${kind}" data-parent="${esc(parent)}" data-task="${id}"><div class="v4-task-title">${badge(t.status)}<strong>${title}</strong></div><select class="v4-task-status">${options(STATUS,t.status)}</select><input class="v4-task-url" type="url" value="${esc(t.url||'')}" placeholder="YouTube URL (optional)"><details><summary>Social Media</summary><div class="v4-social-grid">${PLATFORMS.map(([p,label])=>`<label><span>${label}</span><select data-platform="${p}">${options(SOCIAL,t.social?.[p]||'not_started')}</select></label>`).join('')}</div></details></div>`}
function renderNext(missing){if(!missing.length)return '<div class="v4-empty"><strong>Everything is complete.</strong><p>No missing game productions were found.</p></div>';return `<div class="v4-next-list">${missing.slice(0,100).map((m,i)=>`<div><b>${i+1}</b><span>${esc(m)}</span></div>`).join('')}</div>`}
function taskFor(el){const row=el.closest('.v4-task'),kind=row.dataset.kind,parent=row.dataset.parent,id=row.dataset.task;return kind==='game'?data.production.games[parent].tasks[id]:data.production.seasons[parent].tasks[id]}
function bindControls(){document.querySelectorAll('.v4-task-status').forEach(e=>e.onchange=()=>{taskFor(e).status=e.value;mark();render()});document.querySelectorAll('.v4-task-url').forEach(e=>e.onchange=()=>{taskFor(e).url=e.value.trim();if(e.value.trim()&&taskFor(e).status==='not_started')taskFor(e).status='complete';mark();render()});document.querySelectorAll('[data-platform]').forEach(e=>e.onchange=()=>{taskFor(e).social[e.dataset.platform]=e.value;mark();render()})}
function mark(){dirty=true;status('Changes saved in this browser. Click Publish Changes to update GitHub.','ok')}
async function init(){if(!token()){location.href='index.html';return}$('#menuBtn').onclick=()=>document.querySelector('.admin-sidebar').classList.toggle('open');$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('asgGithubToken');location.href='index.html'};try{const f=await get();sha=f.sha;data=JSON.parse(decode(f.content));ensure();status('Connected • V4 Production Control Center ready','ok');render()}catch(e){status('Could not load production data: '+e.message,'bad')}}
init();
})();